#!/usr/bin/env python3
"""Generate Baseline / Post-hoc / Ours wavs from Mel spectrograms.

This script takes Mel (.npy) inputs and produces:
- baseline_wav: generated by standard DiffWave
- posthoc_wav: baseline audio with post-hoc watermark (LSB or spread-spectrum)
- ours_wav: generated by watermarked DiffWave (embedded during reverse diffusion)

It also writes a new manifest CSV with paths:
id,text,gt_wav,gt_mel,baseline_wav,posthoc_wav,ours_wav,posthoc_result
"""

from __future__ import annotations

import argparse
import json
import os
import random
import re
from pathlib import Path
from typing import Dict, Optional, Tuple

import numpy as np
import torch
import torchaudio

try:
    import pandas as pd
except Exception:
    pd = None  # type: ignore

from diffwave.model import DiffWave
from diffwave.params import AttrDict, params as base_params


_fingerprint_global = None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate Baseline/Post-hoc/Ours wav sets from Mel .npy files.")
    parser.add_argument("--input_manifest_csv", type=str, required=True, help="Input CSV with at least id + mel path columns.")
    parser.add_argument("--output_manifest_csv", type=str, default="results/generated_manifest.csv", help="Output CSV for evaluation.")
    parser.add_argument("--output_dir", type=str, default="results/generated_wavs", help="Output root directory.")

    parser.add_argument("--baseline_ckpt", type=str, required=True, help="Baseline DiffWave checkpoint (.pt).")
    parser.add_argument("--mask_ckpt", type=str, required=True, help="Mask checkpoint (.pth).")
    parser.add_argument("--wm_ckpt", type=str, required=True, help="Watermarked DiffWave checkpoint (.pth).")

    parser.add_argument("--device", type=str, default=("cuda" if torch.cuda.is_available() else "cpu"), help="Inference device.")
    parser.add_argument("--fast", action="store_true", help="Use fast sampling schedule.")
    parser.add_argument("--seed", type=int, default=1234, help="Sampling seed (baseline/ours fairness).")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing generated wavs.")
    parser.add_argument("--max_samples", type=int, default=None, help="Optional cap for quick run.")

    parser.add_argument("--target_bits", type=str, default="1011001010110010", help="Global target watermark bits.")
    parser.add_argument("--posthoc_method", type=str, default="lsb", choices=["lsb", "spread"], help="Post-hoc watermark method.")
    parser.add_argument("--spread_alpha", type=float, default=0.003, help="Embedding strength for spread-spectrum.")
    parser.add_argument(
        "--systems",
        type=str,
        default="Baseline,Post-hoc,Ours",
        help="Comma-separated systems to generate: Baseline, Post-hoc, Ours. Post-hoc requires Baseline.",
    )

    parser.add_argument("--col_id", type=str, default="id", help="Input manifest ID column.")
    parser.add_argument("--col_mel", type=str, default="mel_npy", help="Input manifest mel-path column.")
    parser.add_argument("--col_text", type=str, default="text", help="Input manifest text column (optional).")
    parser.add_argument("--col_gt_wav", type=str, default="gt_wav", help="Input manifest gt_wav column (optional).")
    parser.add_argument("--col_gt_mel", type=str, default="gt_mel", help="Input manifest gt_mel column (optional).")

    return parser.parse_args()


def ensure_dependencies() -> None:
    if pd is None:
        raise RuntimeError("Missing required package: pandas")


def normalize_state_dict(sd: dict) -> dict:
    if isinstance(sd, dict) and ("state_dict" in sd) and isinstance(sd["state_dict"], dict):
        sd = sd["state_dict"]
    if isinstance(sd, dict) and ("model" in sd) and isinstance(sd["model"], dict):
        sd = sd["model"]
    if isinstance(sd, dict) and any(k.startswith("module.") for k in sd.keys()):
        sd = {k.replace("module.", "", 1): v for k, v in sd.items()}
    return sd


def maybe_fix_spectrogram_shape(spectrogram: torch.Tensor, n_mels: int) -> torch.Tensor:
    if spectrogram is None:
        return spectrogram
    if not torch.is_tensor(spectrogram):
        spectrogram = torch.as_tensor(spectrogram)

    if spectrogram.ndim == 2:
        if spectrogram.shape[0] == n_mels:
            return spectrogram
        if spectrogram.shape[1] == n_mels:
            return spectrogram.transpose(0, 1).contiguous()
        return spectrogram

    if spectrogram.ndim == 3:
        if spectrogram.shape[1] == n_mels:
            return spectrogram
        if spectrogram.shape[2] == n_mels:
            return spectrogram.permute(0, 2, 1).contiguous()
        return spectrogram

    return spectrogram


def set_seed(seed: int) -> None:
    torch.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def sanitize_name(name: str) -> str:
    name = str(name).strip()
    if not name:
        name = "sample"
    name = re.sub(r"[^a-zA-Z0-9_\-\.]+", "_", name)
    return name


def resolve_path(path_text: str, base_dir: str) -> str:
    path_text = str(path_text).strip()
    if not path_text:
        return path_text
    p = Path(path_text)
    if p.is_absolute():
        return str(p)
    return str((Path(base_dir) / p).resolve())


def bits_to_fingerprint(bits: str, device: torch.device, finger_dim: int, batch: int = 1) -> torch.Tensor:
    bits = "".join(c for c in str(bits).strip() if c in "01")
    bits = bits.ljust(finger_dim, "0")[:finger_dim]
    vec = torch.tensor([float(c) for c in bits], dtype=torch.float32, device=device).unsqueeze(0)
    if batch > 1:
        vec = vec.repeat(batch, 1)
    return vec


def compute_sampling_mapping(model_params, fast_sampling: bool) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    training_noise_schedule = np.array(model_params.noise_schedule)
    inference_noise_schedule = (
        np.array(model_params.inference_noise_schedule) if fast_sampling else training_noise_schedule
    )

    talpha = 1 - training_noise_schedule
    talpha_cum = np.cumprod(talpha)

    beta = inference_noise_schedule
    alpha = 1 - beta
    alpha_cum = np.cumprod(alpha)

    t_map = []
    for s in range(len(inference_noise_schedule)):
        for t in range(len(training_noise_schedule) - 1):
            if talpha_cum[t + 1] <= alpha_cum[s] <= talpha_cum[t]:
                twiddle = (talpha_cum[t] ** 0.5 - alpha_cum[s] ** 0.5) / (
                    talpha_cum[t] ** 0.5 - talpha_cum[t + 1] ** 0.5
                )
                t_map.append(t + twiddle)
                break
    return alpha, alpha_cum, np.array(t_map, dtype=np.float32)


def load_diffwave_model(model_ckpt: str, device: torch.device) -> DiffWave:
    ckpt_path = Path(model_ckpt)
    if ckpt_path.is_dir():
        ckpt_path = ckpt_path / "diffwave.pt"
    if not ckpt_path.exists():
        raise FileNotFoundError(f"Baseline checkpoint not found: {ckpt_path}")

    raw = torch.load(str(ckpt_path), map_location=device)
    state = raw["model"] if isinstance(raw, dict) and "model" in raw else normalize_state_dict(raw)

    model = DiffWave(AttrDict(base_params)).to(device)
    model.load_state_dict(state, strict=True)
    model.eval()
    return model


def _wm_hook_fn(module, hook_args):
    x = hook_args[0]
    fp = _fingerprint_global
    if fp is None:
        raise RuntimeError("fingerprint is None. Please set fingerprint before Ours inference.")
    if fp.device != x.device:
        fp = fp.to(x.device, non_blocking=True)
    return [x, fp]


def build_watermarked_model(
    baseline_ckpt: str,
    mask_ckpt: str,
    wm_ckpt: str,
    finger_dim: int,
    device: torch.device,
) -> DiffWave:
    if not str(device).startswith("cuda"):
        raise RuntimeError("Watermarked model construction requires CUDA in this repo (base_network uses .cuda()).")

    import torch.nn as nn
    from base_network import get_fingerprint, get_mask_conv
    from utils import load_model_state

    baseline_model_path = Path(baseline_ckpt)
    if baseline_model_path.is_dir():
        baseline_model_path = baseline_model_path / "diffwave.pt"

    ori_ckpt = torch.load(str(baseline_model_path), map_location=device)
    wm_model = DiffWave(AttrDict(base_params)).to(device)
    wm_model.load_state_dict(ori_ckpt["model"], strict=True)
    wm_model.eval()

    for p in wm_model.parameters():
        p.requires_grad = False

    output_layers = []
    for name, layer in reversed(list(wm_model.named_modules())):
        if isinstance(layer, nn.Conv1d) and ("output_projection" in name):
            output_layers.append((name, layer))
            if len(output_layers) == 5:
                break
    if len(output_layers) < 5:
        raise RuntimeError("Not enough output_projection layers to embed watermark (need 5).")

    for name, _layer in output_layers:
        parts = name.split(".")
        temp = wm_model
        for i, part in enumerate(parts):
            if i == len(parts) - 1:
                setattr(temp, part, get_mask_conv(getattr(temp, part), device))
            else:
                temp = getattr(temp, part)

    mask_state = torch.load(mask_ckpt, map_location=device)
    wm_model = load_model_state(wm_model, normalize_state_dict(mask_state))

    for p in wm_model.parameters():
        p.requires_grad = False

    for name, layer in reversed(list(wm_model.named_modules())):
        if isinstance(layer, get_mask_conv):
            parts = name.split(".")
            temp = wm_model
            for i, part in enumerate(parts):
                if i == len(parts) - 1:
                    setattr(temp, part, get_fingerprint(getattr(temp, part), finger_dim))
                else:
                    temp = getattr(temp, part)

    for _name, layer in reversed(list(wm_model.named_modules())):
        if isinstance(layer, get_fingerprint):
            if hasattr(layer, "w_mask"):
                layer.w_mask[layer.w_mask < 3] = 0
                layer.w_mask[layer.w_mask >= 3] = 6
            if hasattr(layer, "set_mask"):
                layer.set_mask()

    wm_state = torch.load(wm_ckpt, map_location=device)
    wm_model.load_state_dict(normalize_state_dict(wm_state), strict=True)

    # Important: newly replaced watermark submodules may stay on CPU by default.
    # Force a full model device move to keep all tensors on the same device.
    wm_model = wm_model.to(device)

    for _name, layer in wm_model.named_modules():
        if isinstance(layer, get_fingerprint):
            if hasattr(layer, "w_mask"):
                layer.w_mask[layer.w_mask < 3] = 0
                layer.w_mask[layer.w_mask >= 3] = 6
            if hasattr(layer, "set_mask"):
                layer.set_mask()
            layer.register_forward_pre_hook(_wm_hook_fn)

    wm_model.eval()
    return wm_model


def predict_audio(
    model: DiffWave,
    spectrogram: torch.Tensor,
    device: torch.device,
    fast_sampling: bool,
) -> Tuple[torch.Tensor, int]:
    alpha, alpha_cum, t_map = compute_sampling_mapping(model.params, fast_sampling)
    beta = np.array(model.params.inference_noise_schedule) if fast_sampling else np.array(model.params.noise_schedule)

    with torch.no_grad():
        spectrogram = maybe_fix_spectrogram_shape(spectrogram, int(model.params.n_mels))
        if spectrogram.ndim == 2:
            spectrogram = spectrogram.unsqueeze(0)
        spectrogram = spectrogram.float().to(device)

        audio = torch.randn(
            spectrogram.shape[0],
            model.params.hop_samples * spectrogram.shape[-1],
            device=device,
        )

        for n in range(len(alpha) - 1, -1, -1):
            c1 = 1.0 / (alpha[n] ** 0.5)
            c2 = beta[n] / ((1.0 - alpha_cum[n]) ** 0.5)
            step = torch.tensor([t_map[n]], device=device)
            model_out = model(audio, spectrogram, step).squeeze(1)
            audio = c1 * (audio - c2 * model_out)
            if n > 0:
                noise = torch.randn_like(audio)
                sigma = ((1.0 - alpha_cum[n - 1]) / (1.0 - alpha_cum[n]) * beta[n]) ** 0.5
                audio = audio + sigma * noise
            audio = torch.clamp(audio, -1.0, 1.0)

    return audio, int(model.params.sample_rate)


def _to_int16_numpy(wav: torch.Tensor) -> np.ndarray:
    x = wav.squeeze(0).detach().cpu().numpy()
    x = np.clip(x, -1.0, 1.0)
    return np.round(x * 32767.0).astype(np.int16)


def _from_int16_numpy(x: np.ndarray) -> torch.Tensor:
    y = x.astype(np.float32) / 32767.0
    y = np.clip(y, -1.0, 1.0)
    return torch.from_numpy(y).unsqueeze(0)


def posthoc_embed_lsb(wav: torch.Tensor, bits: str) -> torch.Tensor:
    bits_arr = np.array([int(c) for c in bits], dtype=np.int32)
    x_i16 = _to_int16_numpy(wav)
    x_i32 = x_i16.astype(np.int32)

    repeats = int(np.ceil(len(x_i32) / len(bits_arr)))
    seq = np.tile(bits_arr, repeats)[: len(x_i32)]

    y_i32 = (x_i32 & ~1) | seq
    y_i16 = np.clip(y_i32, -32768, 32767).astype(np.int16)
    return _from_int16_numpy(y_i16)


def posthoc_decode_lsb(wav: torch.Tensor, bit_len: int) -> str:
    x_i16 = _to_int16_numpy(wav)
    lsb = (x_i16.astype(np.int32) & 1).astype(np.int32)
    bits = []
    for i in range(bit_len):
        vals = lsb[i::bit_len]
        if len(vals) == 0:
            bits.append("0")
        else:
            bits.append("1" if int(np.round(np.mean(vals))) >= 1 else "0")
    return "".join(bits)


def _pn_sequence(length: int, seed: int) -> np.ndarray:
    rng = np.random.RandomState(seed)
    seq = rng.choice([-1.0, 1.0], size=(length,)).astype(np.float32)
    return seq


def posthoc_embed_spread(wav: torch.Tensor, bits: str, alpha: float, seed: int) -> torch.Tensor:
    x = wav.squeeze(0).detach().cpu().numpy().astype(np.float32)
    t = len(x)
    y = np.copy(x)

    num_bits = len(bits)
    for i, b in enumerate(bits):
        pn = _pn_sequence(t, seed + 9973 * i)
        sign = 1.0 if b == "1" else -1.0
        y += (alpha / max(1, num_bits)) * sign * pn

    y = np.clip(y, -1.0, 1.0)
    return torch.from_numpy(y).unsqueeze(0)


def posthoc_decode_spread(wav: torch.Tensor, bit_len: int, seed: int) -> str:
    x = wav.squeeze(0).detach().cpu().numpy().astype(np.float32)
    t = len(x)
    out = []
    for i in range(bit_len):
        pn = _pn_sequence(t, seed + 9973 * i)
        corr = float(np.dot(x, pn) / max(1, t))
        out.append("1" if corr >= 0.0 else "0")
    return "".join(out)


def load_manifest(args: argparse.Namespace) -> pd.DataFrame:
    in_path = Path(args.input_manifest_csv)
    if not in_path.exists():
        raise FileNotFoundError(f"input_manifest_csv not found: {in_path}")

    df = pd.read_csv(str(in_path))

    if args.col_id not in df.columns:
        raise ValueError(f"Missing required ID column: {args.col_id}")

    mel_col = args.col_mel
    if mel_col not in df.columns:
        if args.col_gt_mel in df.columns:
            mel_col = args.col_gt_mel
            print(f"[Info] mel column '{args.col_mel}' not found, fallback to '{args.col_gt_mel}'.")
        else:
            raise ValueError(f"Missing mel column: {args.col_mel} (and fallback {args.col_gt_mel})")

    base_dir = str(in_path.parent.resolve())
    resolved = []
    for _, row in df.iterrows():
        mel_path = resolve_path(row[mel_col], base_dir)
        resolved.append(mel_path)

    df = df.copy()
    df["__mel_path__"] = resolved

    before = len(df)
    df = df[df["__mel_path__"].apply(lambda p: isinstance(p, str) and os.path.exists(p))].reset_index(drop=True)
    dropped = before - len(df)
    if dropped > 0:
        print(f"[Warn] Dropped {dropped} rows with missing mel files.")

    if args.max_samples is not None:
        df = df.iloc[: max(0, int(args.max_samples))].copy()

    if len(df) == 0:
        raise RuntimeError("No valid rows in input manifest after mel-path validation.")

    return df


def ensure_dirs(output_root: str) -> Dict[str, str]:
    root = Path(output_root)
    dirs = {
        "baseline": str((root / "baseline").resolve()),
        "posthoc": str((root / "posthoc").resolve()),
        "ours": str((root / "ours").resolve()),
        "posthoc_results": str((root / "posthoc_results").resolve()),
    }
    for p in dirs.values():
        os.makedirs(p, exist_ok=True)
    return dirs


def parse_systems(systems_text: str) -> set[str]:
    aliases = {
        "baseline": "Baseline",
        "posthoc": "Post-hoc",
        "post-hoc": "Post-hoc",
        "ours": "Ours",
    }
    out = set()
    for item in str(systems_text).split(","):
        key = item.strip().lower()
        if not key:
            continue
        if key not in aliases:
            raise ValueError(f"Unknown system in --systems: {item}")
        out.add(aliases[key])
    if not out:
        raise ValueError("--systems must include at least one system.")
    if "Post-hoc" in out:
        out.add("Baseline")
    return out


def main() -> None:
    args = parse_args()
    ensure_dependencies()

    device = torch.device(args.device)
    if not torch.cuda.is_available() and str(device).startswith("cuda"):
        raise RuntimeError("CUDA requested but not available.")

    target_bits_raw = "".join(c for c in str(args.target_bits).strip() if c in "01")
    if len(target_bits_raw) == 0:
        raise ValueError("target_bits must include at least one binary character.")
    systems_to_generate = parse_systems(args.systems)

    df = load_manifest(args)
    out_dirs = ensure_dirs(args.output_dir)

    baseline_model = None
    if "Baseline" in systems_to_generate:
        print("[Load] baseline DiffWave checkpoint...")
        baseline_model = load_diffwave_model(args.baseline_ckpt, device)

    wm_model = None
    if "Ours" in systems_to_generate:
        print("[Load] watermarked DiffWave checkpoint stack (baseline + mask + wm)...")
        wm_model = build_watermarked_model(
            baseline_ckpt=args.baseline_ckpt,
            mask_ckpt=args.mask_ckpt,
            wm_ckpt=args.wm_ckpt,
            finger_dim=len(target_bits_raw),
            device=device,
        )

    output_rows = []

    global _fingerprint_global

    for idx, row in df.iterrows():
        sample_id = sanitize_name(row[args.col_id])
        mel_path = row["__mel_path__"]

        base_out = os.path.join(out_dirs["baseline"], f"{sample_id}_baseline.wav")
        post_out = os.path.join(out_dirs["posthoc"], f"{sample_id}_posthoc.wav")
        ours_out = os.path.join(out_dirs["ours"], f"{sample_id}_ours.wav")
        post_res = os.path.join(out_dirs["posthoc_results"], f"{sample_id}_posthoc_result.json")

        required_paths = []
        if "Baseline" in systems_to_generate:
            required_paths.append(base_out)
        if "Post-hoc" in systems_to_generate:
            required_paths.extend([post_out, post_res])
        if "Ours" in systems_to_generate:
            required_paths.append(ours_out)
        need_gen = args.overwrite or any(not os.path.exists(p) for p in required_paths)

        if need_gen:
            mel = torch.from_numpy(np.load(mel_path)).float()

            sr = int(base_params.sample_rate)

            baseline_audio = None
            if "Baseline" in systems_to_generate:
                if baseline_model is None:
                    raise RuntimeError("Baseline requested but baseline_model is not loaded.")
                set_seed(args.seed)
                baseline_audio, sr = predict_audio(
                    model=baseline_model,
                    spectrogram=mel,
                    device=device,
                    fast_sampling=args.fast,
                )
                baseline_audio = baseline_audio[:1].detach().cpu()
                torchaudio.save(base_out, baseline_audio, sample_rate=int(sr))

            if "Post-hoc" in systems_to_generate:
                if baseline_audio is None:
                    if not os.path.exists(base_out):
                        raise RuntimeError(f"Post-hoc requested but missing baseline wav: {base_out}")
                    baseline_audio, sr = torchaudio.load(base_out)
                if args.posthoc_method == "lsb":
                    posthoc_audio = posthoc_embed_lsb(baseline_audio, target_bits_raw)
                    posthoc_pred_bits = posthoc_decode_lsb(posthoc_audio, len(target_bits_raw))
                else:
                    posthoc_audio = posthoc_embed_spread(
                        baseline_audio,
                        target_bits_raw,
                        alpha=float(args.spread_alpha),
                        seed=int(args.seed),
                    )
                    posthoc_pred_bits = posthoc_decode_spread(posthoc_audio, len(target_bits_raw), seed=int(args.seed))
                torchaudio.save(post_out, posthoc_audio, sample_rate=int(sr))
                with open(post_res, "w", encoding="utf-8") as f:
                    json.dump(
                        {
                            "id": sample_id,
                            "method": args.posthoc_method,
                            "target_bits": target_bits_raw,
                            "pred_bits": posthoc_pred_bits,
                            "baseline_wav": base_out,
                            "posthoc_wav": post_out,
                        },
                        f,
                        ensure_ascii=False,
                        indent=2,
                    )

            if "Ours" in systems_to_generate:
                if wm_model is None:
                    raise RuntimeError("Ours requested but wm_model is not loaded.")
                _fingerprint_global = bits_to_fingerprint(
                    target_bits_raw,
                    device=device,
                    finger_dim=len(target_bits_raw),
                    batch=1,
                ).to(device)
                set_seed(args.seed)
                ours_audio, sr_ours = predict_audio(
                    model=wm_model,
                    spectrogram=mel,
                    device=device,
                    fast_sampling=args.fast,
                )
                ours_audio = ours_audio[:1].detach().cpu()
                torchaudio.save(ours_out, ours_audio, sample_rate=int(sr_ours))

        out_row = dict(row)
        out_row.pop("__mel_path__", None)

        out_row["id"] = sample_id
        out_row["baseline_wav"] = str(Path(base_out).resolve())
        out_row["posthoc_wav"] = str(Path(post_out).resolve())
        out_row["ours_wav"] = str(Path(ours_out).resolve())
        out_row["posthoc_result"] = str(Path(post_res).resolve())

        if "text" not in out_row:
            out_row["text"] = str(row[args.col_text]) if args.col_text in row else ""
        if "gt_wav" not in out_row:
            out_row["gt_wav"] = str(row[args.col_gt_wav]) if args.col_gt_wav in row else ""
        if "gt_mel" not in out_row:
            out_row["gt_mel"] = str(row[args.col_gt_mel]) if args.col_gt_mel in row else str(mel_path)

        output_rows.append(out_row)

        if (idx + 1) % 10 == 0 or (idx + 1) == len(df):
            print(f"[Progress] generated {idx + 1}/{len(df)}")

    out_df = pd.DataFrame(output_rows)

    preferred_order = ["id", "text", "gt_wav", "gt_mel", "baseline_wav", "posthoc_wav", "ours_wav", "posthoc_result"]
    for col in preferred_order:
        if col not in out_df.columns:
            out_df[col] = ""
    rest_cols = [c for c in out_df.columns if c not in preferred_order]
    out_df = out_df[preferred_order + rest_cols]

    out_manifest = Path(args.output_manifest_csv)
    out_manifest.parent.mkdir(parents=True, exist_ok=True)
    out_df.to_csv(str(out_manifest), index=False, encoding="utf-8")

    print("\n[Done] Generation completed.")
    print(f"[Saved] Output manifest: {str(out_manifest.resolve())}")
    print(f"[Saved] Baseline wav dir: {out_dirs['baseline']}")
    print(f"[Saved] Post-hoc wav dir: {out_dirs['posthoc']}")
    print(f"[Saved] Ours wav dir: {out_dirs['ours']}")


if __name__ == "__main__":
    main()
